### ISSUE TITLE
A selfish request

### ISSUE THREAD

**Issue by MichaelCharles** [MichaelCharlesCo/datasciencecoursera#2]
Hey there, my name is Michael Charles Aubrey, and on the internet, I mostly go by Michael Charles. 

I'd really, really love to have the MichaelCharles username on GitHub. 

It seems like you're just using this to host some old data science coursework or something like that? I would be overjoyed if you agreed to change your username to something else and let me have the MichaelCharles username. 

Anyway, shot in the dark. Not sure if you ever check this. And I totally recognize and respect that despite you not using this account you might still want to hang onto the name. 

I'm making this an issue her in hopes that you see it, because I don't otherwise know how I can reach out to you.

**Comment by MichaelCharlesCo** [comment]
Done.  If you find any incorrect references to the old MichaelCharles,
please let me know or redirect them to MichaelCharlesCo.

**Comment by MichaelCharles** [comment]
You're very exceedingly kind!

>  If you find any incorrect references to the old MichaelCharles, please let me know or redirect them to MichaelCharlesCo.

Of course, thank you!
